prompt = "> "
placeholder = ""
message = ""
minimal_lines = false
lines = 15
width = 30
window_x = -1
window_y = -1
font = "monospace"
icon_theme = "default"
icons_enabled = true
image_size_ratio = 0.5
horizontal_pad = 40
vertical_pad = 8
inner_pad = 0
line_height = 22
show_paths = false
hide_before_typing = false
auto_select = false
match_counter = false
fields = "filename,name,generic"
match_mode = "fzf"
terminal = "xterm -e {cmd}"
password_character = "*"

[colors]
background = "#fdf6e3ff"
text = "#657b83ff"
message = "#657b83ff"
prompt = "#586e75ff"
placeholder = "#93a1a1ff"
input = "#657b83ff"
match = "#cb4b16ff"
selection = "#eee8d5ff"
selection-text = "#586e75ff"
selection-match = "#cb4b16ff"
counter = "#93a1a1ff"
border = "#002b36ff"

[border]
width = 1
radius = 10
